platform :ios, '9.0'

target 'ReactNativeTypescript' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeTypescript
  pod 'Firebase/Core', '~> 5.9.0'

end
