platform :ios, '9.0'

target 'ReactNativeTypescript' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeTypescript
  pod 'Firebase/Core', '~> 5.9.0'

  #pod 'Firebase/AdMob', '~> 5.9.0'
  #pod 'Firebase/Analytics', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'Firebase/Firestore', '~> 5.9.0'
  #pod 'Firebase/Crash', '~> 5.9.0'
  #pod 'Firebase/Database', '~> 5.9.0'
  #pod 'Firebase/DynamicLinks', '~> 5.9.0'
  #pod 'Firebase/Invites', '~> 5.9.0'
  #pod 'Firebase/Messaging', '~> 5.9.0'
  #pod 'Firebase/Performance', '~> 5.9.0'
  #pod 'Firebase/RemoteConfig', '~> 5.9.0'
  #pod 'Firebase/Storage', '~> 5.9.0'
end
